### ISSUE TITLE
The issue with downloading model links

### ISSUE THREAD

**Issue by wertyuiolxt** [ming053l/CSAKD#3]
Hello, I am very interested in your CSAKD, but I noticed that in README.md, the download links for Pre trained Teacher Model and Pre trained Student Model are the same. After opening them, only the sharing about Pre-trained Student Model is available. I would like to know if this is my oversight. I look forward to your reply.

**Comment by ming053l** [comment]
Thanks for your insterested!

Woo! This is my fault, sorry. I share the same link for teacher and student ckpt.

I have uploaded the correct link.
